/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2labp2_linsyposso;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.DefaultColorSelectionModel;

/**
 *
 * @author 29164
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_creacionC = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_modelo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        js_velocidad = new javax.swing.JSpinner();
        jb_creado = new javax.swing.JButton();
        jD_carrera = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jl_cronometro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jl_nombreC = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jl_nombreC2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jb_iniciarCarrea = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_Cjugador1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cb_Cjugador2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jb_crearC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jl_marca1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jl_marca2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jl_modelo1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jl_velocidad1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jl_modelo2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jl_velocidad2 = new javax.swing.JLabel();
        jb_iniciar = new javax.swing.JButton();

        jD_creacionC.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CREACION DE CARROS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Marca");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));
        jPanel2.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 120, 280, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Modelo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));
        jPanel2.add(tf_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 220, 280, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Velocidad");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));
        jPanel2.add(js_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 90, 30));

        jb_creado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_creado.setText("Crear");
        jb_creado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_creadoMouseClicked(evt);
            }
        });
        jPanel2.add(jb_creado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        javax.swing.GroupLayout jD_creacionCLayout = new javax.swing.GroupLayout(jD_creacionC.getContentPane());
        jD_creacionC.getContentPane().setLayout(jD_creacionCLayout);
        jD_creacionCLayout.setHorizontalGroup(
            jD_creacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_creacionCLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jD_creacionCLayout.setVerticalGroup(
            jD_creacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("TIEMPO");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jl_cronometro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_cronometro.setForeground(new java.awt.Color(0, 0, 0));
        jl_cronometro.setText("00:00");
        jPanel3.add(jl_cronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 10));

        jl_nombreC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_nombreC.setForeground(new java.awt.Color(0, 0, 0));
        jl_nombreC.setText("jLabel17");
        jPanel3.add(jl_nombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jProgressBar1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 270, 30));

        jl_nombreC2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_nombreC2.setForeground(new java.awt.Color(0, 0, 0));
        jl_nombreC2.setText("jLabel18");
        jPanel3.add(jl_nombreC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jProgressBar2.setForeground(new java.awt.Color(51, 255, 51));
        jPanel3.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 270, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("PROCESO");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jb_iniciarCarrea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_iniciarCarrea.setText("Iniciar");
        jb_iniciarCarrea.setToolTipText("");
        jPanel3.add(jb_iniciarCarrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        javax.swing.GroupLayout jD_carreraLayout = new javax.swing.GroupLayout(jD_carrera.getContentPane());
        jD_carrera.getContentPane().setLayout(jD_carreraLayout);
        jD_carreraLayout.setHorizontalGroup(
            jD_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_carreraLayout.setVerticalGroup(
            jD_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PARTIDA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jugador 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        cb_Cjugador1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_Cjugador1ItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_Cjugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jugador 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        cb_Cjugador2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_Cjugador2ItemStateChanged(evt);
            }
        });
        jPanel1.add(cb_Cjugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("VS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jb_crearC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_crearC.setText("Crear Carro");
        jb_crearC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearCMouseClicked(evt);
            }
        });
        jPanel1.add(jb_crearC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Marca");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jl_marca1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_marca1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jl_marca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 50, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Marca");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jl_marca2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_marca2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jl_marca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 60, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Modelo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 60, -1));

        jl_modelo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_modelo1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jl_modelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 70, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Velocidad");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jl_velocidad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_velocidad1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jl_velocidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 60, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Modelo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jl_modelo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_modelo2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jl_modelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 80, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Velocidad");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        jl_velocidad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_velocidad2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jl_velocidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        jb_iniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_iniciar.setText("Iniciar");
        jb_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_iniciarMouseClicked(evt);
            }
        });
        jPanel1.add(jb_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearCMouseClicked
        jD_creacionC.pack();
        jD_creacionC.setModal(true);
        jD_creacionC.setLocationRelativeTo(this);
        jD_creacionC.setVisible(true);
    }//GEN-LAST:event_jb_crearCMouseClicked

    private void jb_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_iniciarMouseClicked
        jD_carrera.pack();
        jD_carrera.setModal(true);
        jD_carrera.setLocationRelativeTo(this);
        jD_carrera.setVisible(true);
    }//GEN-LAST:event_jb_iniciarMouseClicked

    private void jb_creadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_creadoMouseClicked
        Carro c = new Carro(tf_marca.getText(), tf_modelo.getText(), (int) js_velocidad.getValue());
        AdminCarro car = new AdminCarro("./Carros.exa");
        car.cargarArchivo();
        car.setCarro(c);
        car.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Carro Creado Correctamente");
        tf_marca.setText("");
        tf_modelo.setText("");
        js_velocidad.setValue(0);
        DefaultComboBoxModel mod1 =  (DefaultComboBoxModel) cb_Cjugador1.getModel();
        for (Carro cr : car.lista) {
            mod1.addElement(cr);
        }
        cb_Cjugador1.setModel(mod1);
        DefaultComboBoxModel mod2 =  (DefaultComboBoxModel) cb_Cjugador2.getModel();
        for (Carro cr : car.lista) {
            mod2.addElement(cr);
        }
        cb_Cjugador2.setModel(mod2);
    }//GEN-LAST:event_jb_creadoMouseClicked

    private void cb_Cjugador1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_Cjugador1ItemStateChanged
        Carro temp = (Carro) cb_Cjugador1.getSelectedItem();
        if (temp != null) {
            jl_marca1.setText(temp.getMarca());
            jl_modelo1.setText(temp.getModelo());
            jl_velocidad1.setText((String.valueOf(temp.getVelocidad())));
        }
        
    }//GEN-LAST:event_cb_Cjugador1ItemStateChanged

    private void cb_Cjugador2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_Cjugador2ItemStateChanged
        Carro temp = (Carro) cb_Cjugador2.getSelectedItem();
        if (temp != null) {
            jl_marca2.setText(temp.getMarca());
            jl_modelo2.setText(temp.getModelo());
            jl_velocidad2.setText((String.valueOf(temp.getVelocidad())));
        }
    }//GEN-LAST:event_cb_Cjugador2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Cjugador1;
    private javax.swing.JComboBox<String> cb_Cjugador2;
    private javax.swing.JDialog jD_carrera;
    private javax.swing.JDialog jD_creacionC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_creado;
    private javax.swing.JButton jb_crearC;
    private javax.swing.JButton jb_iniciar;
    private javax.swing.JButton jb_iniciarCarrea;
    private javax.swing.JLabel jl_cronometro;
    private javax.swing.JLabel jl_marca1;
    private javax.swing.JLabel jl_marca2;
    private javax.swing.JLabel jl_modelo1;
    private javax.swing.JLabel jl_modelo2;
    private javax.swing.JLabel jl_nombreC;
    private javax.swing.JLabel jl_nombreC2;
    private javax.swing.JLabel jl_velocidad1;
    private javax.swing.JLabel jl_velocidad2;
    private javax.swing.JSpinner js_velocidad;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    // End of variables declaration//GEN-END:variables
}
